export const EVENT_NAME = {
  INITIAL: "INITIAL",
  HTTP_REQUEST_STATUS: "HTTP_REQUEST_STATUS",
  ADD_STOP: "ADD_STOP",
  STOP_ADDED: "STOP_ADDED",
  STOP_MODIFIED: "STOP_MODIFIED",
  CHANGE_SEARCH_DISTANCE: "CHANGE_SEARCH_DISTANCE"
} as const;

export const BASE_ORDINAL_NUMBER = "01";

export const DEFAULT_SEARCH_DISTANCE = 500;
export const SEARCH_DISTANCE = [DEFAULT_SEARCH_DISTANCE, 1000, 2500, 5000] as const;

export const MILLISECONDS_IN_SECOND = 1000;

export const STOP_CARD_DRAG_DELAY = 500;
