name: release
on:
  push:
    branches:
      - main

env:
  NG_APP_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  HUSKY: 0

jobs:
  release:
    name: Build Android and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install Dependencies
        run: pnpm i

      - name: Bump Build Version
        id: version-bump-build
        uses: "phips28/gh-action-bump-version@master"
        with:
          skip-commit: true
          skip-tag: true
          skip-push: true

      - name: Set Build Version
        run: |
          echo "NG_APP_VERSION=${{ steps.version-bump-build.outputs.newTag }}" >> "$GITHUB_ENV"
          git restore package.json

      - name: Build Web Application
        run: pnpm build:prod

      - name: Generate Sentry Source Maps
        run: pnpm sentry:sourcemaps

      - name: Copy Web Assets
        run: npx cap copy

      - name: Update Native Dependencies
        run: npx cap update

      - name: Build Native Application
        run: cd android && ./gradlew assembleRelease

      - name: Extract Android Signing Key
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE }}" > android/release.jks.base64
          base64 -d android/release.jks.base64 > android/release.decrypted.jks

      - name: Sign Build
        run: |
          sudo apt install -y zipalign apksigner
          zipalign -v 4 android/app/build/outputs/apk/release/app-release-unsigned.apk android/app/build/outputs/apk/release/app-release-unsigned-aligned.apk
          apksigner sign --ks android/release.decrypted.jks --ks-key-alias release --ks-pass pass:"${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" --out android/app/build/outputs/apk/release/app-release-signed.apk android/app/build/outputs/apk/release/app-release-unsigned-aligned.apk

      - name: Bump Release Version
        id: version-bump-release
        uses: "phips28/gh-action-bump-version@master"

      - name: Generate Changelog
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          tag: ${{ steps.version-bump-release.outputs.newTag }}
          includeInvalidCommits: true
          writeToFile: false
          reverseOrder: true
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: ${{ steps.version-bump-release.outputs.newTag }}
          body: ${{ steps.changelog.outputs.changes }}
          artifacts: android/app/build/outputs/apk/release/app-release-signed.apk
          token: ${{ secrets.ACCESS_TOKEN }}
