name: build
on:
  push:
    branches:
      - main

env:
  HUSKY: 0

jobs:
  release:
    name: Build Android and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install Dependencies
        run: pnpm i

      - name: Build Web Application
        run: pnpm build

      - name: Copy Web Assets
        run: npx cap copy

      - name: Update Native Dependencies
        run: npx cap update

      - name: Build Native Bundle
        run: cd android && ./gradlew bundle && ./gradlew assembleDebug

      - name: Extract Android Signing Key
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE }}" > android/release.jks.base64
          base64 -d android/release.jks.base64 > android/release.decrypted.jks

      - name: Sign Build
        run: jarsigner -keystore android/release.decrypted.jks -storepass "${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" -signedjar ./android/app/build/outputs/bundle/release/app-release-signed.aab ./android/app/build/outputs/bundle/release/app-release.aab release

      - name: Get Current Version
        id: version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Tag Release
        run: |
          git tag ${{ steps.version.outputs.current-version }}
          git push origin ${{ steps.version.outputs.current-version }}

      - name: Generate Changelog
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          tag: ${{ steps.version.outputs.current-version }}
          includeInvalidCommits: true
          writeToFile: false
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: ${{ steps.version.outputs.current-version }}
          body: ${{ steps.changelog.outputs.changes }}
          artifacts: android/app/build/outputs/bundle/release/app-release-signed.aab,android/app/build/outputs/apk/debug/app-debug.apk
          token: ${{ secrets.ACCESS_TOKEN }}
